version: "2.2"
services:
  backend:
    image: configdjangobackend:latest
    command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/backendservice
    depends_on:
      db:
        condition: service_healthy

  queue:
    build:
      context: . #queue
      dockerfile: Dockerfile
    command: "python3 -u consumer.py"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: config
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
      MYSQL_ROOT_PASSWORD: microservice
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3308:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
volumes:
  dbdata:
